Mon, 05 Dec 2016 11:18:09 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x179f62c>, <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 57689), raddr=('127.0.0.1', 8888)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 48, in read_json
    d = json.loads(raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:20:19 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x172baec>, <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 57689)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 48, in read_json
    d = json.loads(raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:25:55 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x1f2baec>, <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 57750)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 48, in read_json
    print("raw: " + raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:26:02 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x179974c>, <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 57774), raddr=('127.0.0.1', 8888)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 49, in read_json
    d = json.loads(raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:26:34 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x1f2eacc>, <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 57774)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 49, in read_json
    d = json.loads(raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:26:35 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x1f997ac>, <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 57776), raddr=('127.0.0.1', 8888)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 49, in read_json
    d = json.loads(raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:26:37 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x1f341cc>, <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 57776)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 49, in read_json
    d = json.loads(raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:26:38 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x1f9956c>, <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 57777), raddr=('127.0.0.1', 8888)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 49, in read_json
    d = json.loads(raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:28:03 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x1f998ac>, <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 57777), raddr=('127.0.0.1', 8888)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 49, in read_json
    print("raw: " + raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:28:07 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x1f9c4ac>, <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 57789), raddr=('127.0.0.1', 8888)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 50, in read_json
    d = json.loads(raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:30:20 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x1f2f58c>, <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 57789)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 50, in read_json
    d = json.loads(raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mon, 05 Dec 2016 11:30:44 util.py[line:33] ERROR 

network.util
read_json ( (<network.PMDatagram.PMDatagram object at 0x1ef698c>, <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 57802)>), {} )
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/bh/projects/python/pyMessage/network/util.py", line 29, in logged_func
    return func(*args, **kwargs)
  File "/Users/bh/projects/python/pyMessage/network/PMDatagram.py", line 50, in read_json
    d = json.loads(raw_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
